### ISSUE TITLE
Document deployment method

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage-microsite#105]

**Comment by OrkoHunter** [comment]
I too believe the README should have a section about `Contributing` and `Deployment`. Thanks! ✍️

**Comment by OrkoHunter** [comment]
Oh, I see that the website is deployed automatically using GitHub actions, when a PR is merged. Awesome! I'll create a PR to add this to the README.

<img width="662" alt="Screen Shot 2020-04-15 at 15 01 16" src="https://user-images.githubusercontent.com/8065913/79303503-022bcb80-7f2a-11ea-9d90-c4be935f9712.png">
