### ISSUE TITLE
Logo in footer needs to match logo in header

### ISSUE THREAD

**Issue by katz95** [spotify/backstage-microsite#108]
Current logo in footer: <img width="442" alt="Screenshot 2020-03-19 at 12 25 55 PM" src="https://user-images.githubusercontent.com/61153904/77062775-d675fe00-69dc-11ea-94f3-8f750e83d793.png">

Correct logo in header: 
<img width="232" alt="Screenshot 2020-03-19 at 12 26 35 PM" src="https://user-images.githubusercontent.com/61153904/77062819-e7bf0a80-69dc-11ea-94b4-f7ffd52cbda9.png">

**Comment by mateusmarquezini** [comment]
Hi @katz95 !

Does that fix the problem?

Can I open a PR? :smile: 

![backstage_footer_logo](https://user-images.githubusercontent.com/9571906/77200686-d99ae800-6ac9-11ea-9eb3-e7cc99645364.gif)

**Comment by stefanalund** [comment]
Looks nice! We would love a PR! Thanks in advance
