### ISSUE TITLE
Better use of screen width 

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage-microsite#117]
On an iPad (and smaller screens) the text boxes could expand horizontally:

![04FA4442-8377-4418-A903-F2954256CFAA](https://user-images.githubusercontent.com/190856/77850776-f378b100-71d4-11ea-9f1e-5582c636936d.jpeg)

**Comment by mateusmarquezini** [comment]
I found 2 nice options to use, but I see differences between them.

I personally liked the 95% :stuck_out_tongue_winking_eye:

1 - Using the max-width: 100% for the text box 
![issue_117](https://user-images.githubusercontent.com/9571906/78028289-276ae800-7335-11ea-8475-66478196de72.png)

2 - Using max-width: 95% for the text box 
![issue_117_95](https://user-images.githubusercontent.com/9571906/78028290-29cd4200-7335-11ea-9767-49b05f0cb597.png)
