### ISSUE TITLE
Background color change for "The Spotify Story" section

### ISSUE THREAD

**Issue by katz95** [spotify/backstage-microsite#120]
The top of this section should be the same background color as the background color behind the quotation. There shouldn't be stark contrast.

**Currently**
<img width="1438" alt="76857038-e95dc680-6854-11ea-903d-03d47b868652" src="https://user-images.githubusercontent.com/61153904/78054465-67a48780-7382-11ea-8603-218e956012af.png">

**Ideally**
<img width="1023" alt="76857241-52ddd500-6855-11ea-8c15-53b5678a931b" src="https://user-images.githubusercontent.com/61153904/78054482-6ecb9580-7382-11ea-84a3-5e81cf089dda.png">

**Comment by mateusmarquezini** [comment]
Hi @katz95 ! So can we consider the color #000000 to this section?

**Comment by katz95** [comment]
@mateusmarquezini could we make it #121212? 😊thank you!
