### ISSUE TITLE
Question: What is the docs directory for?

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage-microsite#151]
I notice that in addition to the blog posts and website pages, there is a [docs](https://github.com/spotify/backstage-microsite/tree/master/docs) directory, which looks like a documentation of [Backstage](https://github.com/spotify/backstage). It was last updated 3 months ago.

Should we maintain the backstage documentation over here as well? I believe, we do that in the spotify/backstage repository. IMO, if we do not need it, we should remove `docs/` and its contents.

**Comment by stefanalund** [comment]
Haha, that is a great question :)

Full transparency: these docs are part of our internal Backstage documentation. We originally planned to host all the docs for Backstage open source in this repo (i.e. making them available on backstage.io) but we started off keeping things in the main repo.

If you are interested, it would be welcomed to move some (removing stuff that still might not make sense) of these docs into `spotify/backstage`. The rest can be deleted from this repo.

**Comment by OrkoHunter** [comment]
Thanks for the explanation @stefanalund ! I will go through these and move over the docs which are relevant.

**Comment by Rugvip** [comment]
Oh derp, didn't see the discussion in this issue until I was creating #156.

Those docs are pretty old, as in older than 3 months afaik, probably last year at least xP

**Comment by OrkoHunter** [comment]
Oh, no worries @Rugvip ! :D Thanks for creating #156
