### ISSUE TITLE
Change the background color of the Blog page to #121212

### ISSUE THREAD

**Issue by katz95** [spotify/backstage-microsite#159]
### Background color of Blog (needs to be #121212)

<img width="469" alt="Screenshot 2020-04-30 at 11 50 54 AM" src="https://user-images.githubusercontent.com/61153904/80697243-fec34300-8ad8-11ea-90b2-ca030301910d.png">

### Background color of Demos
<img width="515" alt="Screenshot 2020-04-30 at 11 51 04 AM" src="https://user-images.githubusercontent.com/61153904/80697196-ece1a000-8ad8-11ea-8ec2-55c1f36d90ed.png">

**Comment by kazuma0129** [comment]
Hello.  I have submitted a PR for this issue!  Please check it!
