### ISSUE TITLE
Update Favicon to new logo

### ISSUE THREAD

**Issue by katz95** [spotify/backstage-microsite#160]
Hi! We have a new logo that we'd love to update the site favicon with. The favicon should look like the following image. I've attached a ZIP file with all the favicon assets. Let me know if those work for you all. 
![Backstage Identity_Assets_Artwork_RGB_04 Icon_Teal](https://user-images.githubusercontent.com/61153904/80699142-ca9d5180-8adb-11ea-932c-5623c5d0afe8.png)

[favicon_package_v0.16.zip](https://github.com/spotify/backstage-microsite/files/4557612/favicon_package_v0.16.zip)

Attached is a screenshot of some of the instructions from the favicon generator site. They may or may not be relevant haha.
<img width="787" alt="Screenshot 2020-04-30 at 12 14 29 PM" src="https://user-images.githubusercontent.com/61153904/80699389-29fb6180-8adc-11ea-961d-65f9a567abf8.png">

**Comment by kazuma0129** [comment]
I've submitted a PR for this issue!
