### ISSUE TITLE
Update main logo in header

### ISSUE THREAD

**Issue by katz95** [spotify/backstage-microsite#168]
Hi! Would appreciate if someone could update the main logo in the header! I've attached the new logo in a ZIP file!

[03 Logo_Teal.svg.zip](https://github.com/spotify/backstage-microsite/files/4600027/03.Logo_Teal.svg.zip)

<img width="618" alt="Screenshot 2020-05-08 at 5 47 33 PM" src="https://user-images.githubusercontent.com/61153904/81422982-12634f00-9154-11ea-82bc-3262acb15809.png">

**Comment by prajwalMR** [comment]
I would like to work on this
