### ISSUE TITLE
Update Social Media Sharing Image

### ISSUE THREAD

**Issue by katz95** [spotify/backstage-microsite#178]
Hi! Currently, our social media sharing image still reflects our old logo. We'd love it if someone could help us adjust it to show our new logo! Thank you! 🙏 

### Old logo
<img width="547" alt="screen_shot_2020-05-26_at_3 31 21_pm" src="https://user-images.githubusercontent.com/61153904/83604803-0f068c00-a577-11ea-868a-d2688e0df93e.png">

### Ideal version (SVG)
[Logo Gradient on Dark.svg.zip](https://github.com/spotify/backstage-microsite/files/4721433/Logo.Gradient.on.Dark.svg.zip)
![Logo Gradient on Dark](https://user-images.githubusercontent.com/61153904/83604930-4b39ec80-a577-11ea-9d4c-1f7084ab00db.png)

**Comment by hi-matbub** [comment]
Hi @katz95 I'd be happy to take a look at this!

**Comment by stefanalund** [comment]
Fixed in #182
