### ISSUE TITLE
Add new Tech Insights video

### ISSUE THREAD

**Issue by AlleyWei** [spotify/backstage-microsite#181]
We've recently released a new demo video for Tech Insights, and want to include it on: https://backstage.io/demos

Here's the embed URL: https://www.youtube.com/watch?v=K3xz6VAbgH8

Here's the text:

**Manage your tech health**
Instead of manually updating a spreadsheet, what if you had a beautiful dashboard that could give you an instant, interactive picture of your entire org’s tech stack? That’s how we do it at Spotify. With our Tech Insights plugin for Backstage, anyone at Spotify can see which version of which software anyone else at Spotify is using — and a whole a lot more. From managing migrations to fighting tech entropy, Backstage makes managing our tech health actually kind of pleasant.

[WATCH NOW](https://www.youtube.com/watch?v=K3xz6VAbgH8&list=PLf1KFlSkDLIBtMGwRDfaVlKMqTMrjD2yO&index=6)

**Comment by fengypants** [comment]
And we want to use two different URLs — embed link is to standalone video, Watch Now button puts you in the playlist.
